variables:
  DOCKER_REGISTRY: registry.markzhengma.com
  PORT: 3000

before_script:
  - docker pull registry.markzhengma.com/markynode
  - echo "connected to docker registry, ready to start..."
  - pwd

stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - marky-runner
  only:
    - master
  script:
    - echo 'building docker image...'
    - echo ${CONTAINER_NAME}
    - docker build -t ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG} .
    - echo 'pushing docker image to registry'
    - docker push ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}

deploy:
  stage: deploy
  tags:
    - marky-runner
  only:
    - master
  script:
    - echo 'removing older version container...'
    - docker kill ${CI_PROJECT_NAME} && docker rm ${CI_PROJECT_NAME}
    - echo 'running latest container...'
    - docker run -dit --name=${CI_PROJECT_NAME} --restart=always -p ${PORT}:7001 ${DOCKER_REGISTRY}/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}
